name: learn_flutter_2_udemy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  http: ^1.1.2
  provider: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.9
  build_runner: ^2.4.7
  mockito: ^5.4.3
  mocktail: ^1.0.1
  bloc_test: ^9.1.5
  platform: 3.1.2
  file: ^6.1.4



flutter:
  uses-material-design: true
